{% set name = "jupyterlab-translate" %}
{% set version = "1.3.5" %}
{% set hash = "4954fb5fb928ae272d33facd81e30e3aab48a569b00596e82775b5850a7c4c89" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - jupyterlab-translate = jupyterlab_translate.cli:main
    - gettext-extract = jupyterlab_translate.gettext_extract:main

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling >=1.5.0
  run:
    - importlib_metadata
    - babel
    - click
    - copier >=7.0.0
    - copier-templates-extensions
    - crowdin-api-client
    - hatchling >=1.5.0
    - jinja2-time
    - nodejs
    - polib
    - python >=3.7
    - requests

test:
  requires:
    - pip
    # Constrain to fix pip check
    - pydantic <=2.0.0
  commands:
    - pip check
    # The 'compiled' shipped version ends with an error - skipping it
    # - gettext-extract --help
    - jupyterlab-translate --help
  imports:
    - jupyterlab_translate

about:
  home: https://github.com/jupyterlab/jupyterlab-translate
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Jupyterlab Language Pack Translations Helper
  description: |
    Jupyter Translate provides functionality to extract localizable strings
    from Jupyterlab extensions. Extensions can update the `jupyterlab-
    language-packs` repository or provide localization files in the extension
    package.
  doc_url: https://github.com/jupyterlab/jupyterlab-translate
  dev_url: https://github.com/jupyterlab/jupyterlab-translate

extra:
  recipe-maintainers:
    - fcollonval
    - goanpeca
